package com.ej.mappers;

import com.ej.mappers.AutoExample;
import com.ej.models.Auto;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AutoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    int countByExample(AutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    int deleteByExample(AutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    int insert(Auto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    int insertSelective(Auto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    List<Auto> selectByExample(AutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    Auto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") Auto record, @Param("example") AutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    int updateByExample(@Param("record") Auto record, @Param("example") AutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    int updateByPrimaryKeySelective(Auto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    int updateByPrimaryKey(Auto record);
}