package com.ej.models;

public class Auto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto.id
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto.name
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto.id
     *
     * @return the value of auto.id
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto.id
     *
     * @param id the value for auto.id
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto.name
     *
     * @return the value of auto.name
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto.name
     *
     * @param name the value for auto.name
     *
     * @mbggenerated Thu Feb 09 14:16:41 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}